Added new cmcticker coin attribute - can be used to override the defa…
atomiclabs/hyperdex pull request #595
Opened 2019-03-12 17:21 UTC by FreeTrade

…ult ticker when requesting quotes from CoinMarketCap. See HOdlcoin for an example.

Re-enabled HOdlcoin with the HODLC/HODL ticker

2019-05-21 15:52 UTC, sindresorhus requested changes

2019-05-21 15:52 UTC, sindresorhus commented on app/marketmaker/supported-currencies.js
> +		cmcticker: 'HODLKA',
This is not a ticker on CMC.

2019-05-21 15:52 UTC, sindresorhus commented on app/marketmaker/supported-currencies.js
> +		cmcticker: 'HODL',
We don't use CMC anymore, so we need a more generic name for this property.

2019-05-21 15:52 UTC, sindresorhus commented on app/marketmaker/supported-currencies.js
> +const getCurrencyCMCTicker = symbol => {
Same as https://github.com/atomiclabs/hyperdex/pull/595/files#r286099824

2019-05-21 15:53 UTC, sindresorhus commented on app/marketmaker/supported-currencies.js
> +	const coinParams = supportedCurrencies.find(currency => currency.coin === symbol);
`coinParams` => `currency`

2019-05-22 07:33 UTC, FreeTrade commented on app/marketmaker/supported-currencies.js
> +		cmcticker: 'HODLKA',
Yes, asset HODL does not have a CMC ticker, but one must be specified so that it does not automatically use the HODL symbol and gather incorrect data if this asset is re-enable in the future.

2019-05-22 07:34 UTC, FreeTrade commented on app/marketmaker/supported-currencies.js
> +		cmcticker: 'HODL',
symbols/tickers are different at different exchanges, otherwise we'd just use the 'coin' property in all cases. What are we using in place of CMC?

2020-09-14 03:29 UTC, closed without merging